name: "Hello, Actions!"
description: "Greet someone"
author: "hungrybluedev@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Subhomoy's Dockerfile"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
